import { HttpEventType } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatSnackBar } from '@angular/material/snack-bar';
import { debounceTime, distinctUntilChanged } from 'rxjs';
import {
  AiBadgeComponent,
  AiContractClause,
  AiContractReviewResponse,
  AiService,
  DocumentSearchHit,
  DocumentsService,
} from 'shared';
import { AiTabsComponent } from '../ai-tabs.component';

/**
 * Contract Review workspace (PRD Module 16 feature 4). Only reviews an
 * *existing* document (`POST /ai/contracts/{docId}/review` takes no upload
 * body) — an unsaved local file must be uploaded via the Documents module
 * first to get an id, which this page doesn't duplicate; it only offers a
 * search-and-select picker over already-uploaded documents.
 *
 * There is no tracked-changes/redline docx output and no configurable firm
 * playbook — `riskFlags` is a flat list of clause-type names the LLM judged
 * high-risk (derived from `clauses[].riskLevel === 'high'`), not
 * `{rule, severity, explanation}` objects. "Save" builds a plain-text review
 * summary and uploads it as a new version of the reviewed document via the
 * real `DocumentsService.uploadVersion` — there is no AI-specific "apply
 * redline" endpoint to call instead.
 */
@Component({
  selector: 'lf-contract-review-page',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatButtonModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatProgressBarModule,
    AiBadgeComponent,
    AiTabsComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './contract-review.page.html',
  styleUrl: './contract-review.page.scss',
})
export class ContractReviewPage {
  private readonly aiService = inject(AiService);
  private readonly documentsService = inject(DocumentsService);
  private readonly snackBar = inject(MatSnackBar);

  readonly searchControl = new FormControl('', { nonNullable: true });
  readonly searching = signal(false);
  readonly hits = signal<DocumentSearchHit[]>([]);

  readonly selectedDocument = signal<DocumentSearchHit | null>(null);
  readonly reviewing = signal(false);
  readonly reviewError = signal<string | null>(null);
  readonly result = signal<AiContractReviewResponse | null>(null);
  readonly saving = signal(false);

  constructor() {
    this.searchControl.valueChanges
      .pipe(debounceTime(300), distinctUntilChanged(), takeUntilDestroyed())
      .subscribe((q) => {
        if (!q.trim()) {
          this.hits.set([]);
          return;
        }
        this.searching.set(true);
        this.documentsService.search({ q }).subscribe({
          next: (hits) => {
            this.hits.set(hits);
            this.searching.set(false);
          },
          error: () => this.searching.set(false),
        });
      });
  }

  selectDocument(hit: DocumentSearchHit): void {
    this.selectedDocument.set(hit);
    this.hits.set([]);
    this.searchControl.setValue('');
    this.result.set(null);
    this.reviewError.set(null);
  }

  runReview(): void {
    const document = this.selectedDocument();
    if (!document) return;

    this.reviewing.set(true);
    this.reviewError.set(null);
    this.result.set(null);
    this.aiService.reviewContract(document.documentId).subscribe({
      next: (result) => {
        this.reviewing.set(false);
        this.result.set(result);
      },
      error: () => {
        this.reviewing.set(false);
        this.reviewError.set('Contract review failed.');
      },
    });
  }

  isHighRisk(clause: AiContractClause): boolean {
    return clause.riskLevel === 'high';
  }

  saveReviewNotes(): void {
    const document = this.selectedDocument();
    const result = this.result();
    if (!document || !result) return;

    const lines = [
      `Contract review notes — ${document.title}`,
      `Generated by AI — review required before relying on this document.`,
      '',
      ...result.clauses.map(
        (c) => `${c.clauseType} [${c.riskLevel ?? 'unrated'}]: ${c.text ?? '(not found)'}`,
      ),
      '',
      result.riskFlags.length > 0
        ? `High-risk clauses: ${result.riskFlags.join(', ')}`
        : 'No high-risk clauses flagged.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const file = new File([blob], `contract-review-notes-${Date.now()}.txt`, {
      type: 'text/plain',
    });

    this.saving.set(true);
    this.documentsService.uploadVersion(document.documentId, file).subscribe({
      next: (event) => {
        if (event.type === HttpEventType.Response) {
          this.saving.set(false);
          this.snackBar.open('Review notes saved as a new document version.', 'Dismiss', {
            duration: 4000,
          });
        }
      },
      error: () => {
        this.saving.set(false);
        this.snackBar.open('Could not save review notes.', 'Dismiss', { duration: 4000 });
      },
    });
  }
}
